<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-android31.0</TargetFramework>
    <SupportedOSPlatformVersion>26</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationTitle>UABEA Android</ApplicationTitle>
    <ApplicationId>com.potes.uabeaandroid</ApplicationId>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidUseLatestPlatformSdk>true</AndroidUseLatestPlatformSdk>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.1" />
    <PackageReference Include="Avalonia.Android" Version="11.0.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AssetsTools.NET">
      <HintPath>..\Assets\AssetsTools.NET.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <AvaloniaResource Include="Assets\classdata.tpk" />
  </ItemGroup>
</Project>
